# Files for testing.

filegroup(
    name = "sgf_files",
    srcs = glob(["*.sgf"]),
    visibility=["//visibility:public"],
)

filegroup(
    name = "models",
    srcs = glob(["*.pb"]),
    visibility=["//visibility:public"],
)
